---
# GitHub App Secret Configuration
# This file shows how to configure GitHub App credentials for Kubernetes deployment

# Option 1: Using kubectl to create secret from files (RECOMMENDED for production)
# =============================================================================
# This keeps your secrets out of version control
#
# kubectl create secret generic github-app-credentials \
#   --from-literal=app-id=YOUR_APP_ID \
#   --from-literal=installation-id=YOUR_INSTALLATION_ID \
#   --from-file=private-key=/path/to/your-private-key.pem \
#   --namespace=monitoring

---
# Option 2: Using Sealed Secrets (RECOMMENDED for GitOps)
# =============================================================================
# First install sealed-secrets controller:
# kubectl apply -f https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.24.0/controller.yaml
#
# Create a regular secret first:
# kubectl create secret generic github-app-credentials \
#   --from-literal=app-id=YOUR_APP_ID \
#   --from-literal=installation-id=YOUR_INSTALLATION_ID \
#   --from-file=private-key=/path/to/private-key.pem \
#   --namespace=monitoring \
#   --dry-run=client -o yaml > github-app-secret-unsealed.yaml
#
# Seal the secret:
# kubeseal -f github-app-secret-unsealed.yaml -w github-app-sealed-secret.yaml
#
# Apply sealed secret:
# kubectl apply -f github-app-sealed-secret.yaml
#
# Delete unsealed secret file:
# rm github-app-secret-unsealed.yaml

---
# Option 3: Using External Secrets Operator (RECOMMENDED for cloud environments)
# =============================================================================
# Works with AWS Secrets Manager, Azure Key Vault, GCP Secret Manager, HashiCorp Vault, etc.
#
# Example with AWS Secrets Manager:
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-app-credentials
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: github-app-credentials
    creationPolicy: Owner
  data:
  - secretKey: app-id
    remoteRef:
      key: github-app-credentials
      property: app-id
  - secretKey: installation-id
    remoteRef:
      key: github-app-credentials
      property: installation-id
  - secretKey: private-key
    remoteRef:
      key: github-app-credentials
      property: private-key

---
# SecretStore for AWS Secrets Manager
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secretsmanager
  namespace: monitoring
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa

---
# Option 4: Manual Secret (NOT RECOMMENDED for production - for testing only)
# =============================================================================
# WARNING: This stores secrets in plain base64 which is NOT secure
# Only use for local testing/development
#
# To create base64 encoded values:
# echo -n "YOUR_APP_ID" | base64
# echo -n "YOUR_INSTALLATION_ID" | base64
# cat /path/to/private-key.pem | base64
#
apiVersion: v1
kind: Secret
metadata:
  name: github-app-credentials
  namespace: monitoring
  labels:
    app: github-rate-limit-exporter
type: Opaque
data:
  # Replace these with your actual base64-encoded values
  # app-id: <base64-encoded-app-id>
  # installation-id: <base64-encoded-installation-id>
  # private-key: <base64-encoded-private-key-pem-content>

---
# Updated Deployment using GitHub App credentials
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-rate-limit-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-rate-limit-exporter
  template:
    metadata:
      labels:
        app: github-rate-limit-exporter
    spec:
      serviceAccountName: github-rate-limit-exporter
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: exporter
        image: github-rate-limit-checker:latest
        imagePullPolicy: IfNotPresent
        command:
        - python
        - github_rate_limit_checker.py
        - --prometheus-port
        - "9090"
        env:
        # Using GitHub App credentials
        - name: GITHUB_APP_ID
          valueFrom:
            secretKeyRef:
              name: github-app-credentials
              key: app-id
        - name: GITHUB_APP_INSTALLATION_ID
          valueFrom:
            secretKeyRef:
              name: github-app-credentials
              key: installation-id
        - name: GITHUB_APP_PRIVATE_KEY_PATH
          value: /secrets/private-key.pem
        volumeMounts:
        - name: github-app-key
          mountPath: /secrets
          readOnly: true
        - name: tmp
          mountPath: /tmp
        ports:
        - name: metrics
          containerPort: 9090
          protocol: TCP
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1001
          capabilities:
            drop:
            - ALL
        livenessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: github-app-key
        secret:
          secretName: github-app-credentials
          items:
          - key: private-key
            path: private-key.pem
            mode: 0400
      - name: tmp
        emptyDir: {}

---
# Example: How to create the secret using your actual credentials
# =============================================================================
#
# 1. Store your credentials in environment variables (more secure):
#    export GITHUB_APP_ID="123456"
#    export GITHUB_APP_INSTALLATION_ID="987654"
#    export GITHUB_PRIVATE_KEY_PATH="/path/to/your-private-key.pem"
#
# 2. Create the secret:
#    kubectl create secret generic github-app-credentials \
#      --from-literal=app-id="${GITHUB_APP_ID}" \
#      --from-literal=installation-id="${GITHUB_APP_INSTALLATION_ID}" \
#      --from-file=private-key="${GITHUB_PRIVATE_KEY_PATH}" \
#      --namespace=monitoring
#
# 3. Verify the secret was created:
#    kubectl get secret github-app-credentials -n monitoring
#
# 4. (Optional) View secret contents (for debugging):
#    kubectl get secret github-app-credentials -n monitoring -o yaml
